//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 CMV.rc 使用
//
#define IDOK_USER_Manage                3
#define IDOK_ADD_User                   3
#define ID_Delete_User                  4
#define ID_ChangePass                   5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_IPWinStatic                 101
#define IDC_FGWinStatic                 102
#define IDC_MainStatic                  103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_OUTRESULT_TAB               105
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CMVTYPE                     130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDS_PICTURE_VIEW                159
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDS_DATA_TAB                    310
#define IDB_HOME                        315
#define IDB_BITMAP1                     316
#define IDB_HOMELARGE                   316
#define IDB_MEA_LARGE                   318
#define IDI_ICON1                       319
#define IDI_ICON_CM                     319
#define IDB_CM                          323
#define IDB_MATCH_SMALL                 324
#define IDB_CELIBRATIONSMALL            325
#define ID_VIEW_PICTURE                 326
#define IDB_CELIBRATE_LARGE             328
#define IDB_MACTCH_LARGE                329
#define IDB_MEA_ELE_LARGE               331
#define IDR_MENU1                       333
#define IDR_POPUP_EXPLORER1             334
#define IDD_DIALOG_LOGING               334
#define IDB_PNG1                        337
#define IDD_DIALOG_User_Manage          338
#define IDC_MFCCOLORBUTTON1             1006
#define IDC_EDIT_USER_NAME              1007
#define IDC_EDIT_PASSWORD               1008
#define IDC_COMBO_UserList              1008
#define IDC_User_Name                   1010
#define IDC_Org_Password                1011
#define IDC_New_Password                1012
#define IDC_Repeat_Password             1013
#define IDC_CHECK_isAdmin               1014
#define IDC_CHECK_isInpector            1015
#define IDC_User_Note                   1016
#define IDC_User_RegTime                1017
#define IDC_User_LastLogTime            1018
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_CAM_ONE_SHOT                 32773
#define ID_CAM_CAP_MULTI                32774
#define ID_CAM_CONTINUE_CAP             32775
#define ID_WIN_ZOOM_OUT                 32776
#define ID_WIN_ZOOM_IN                  32777
#define ID_WIN_RESTORE                  32778
#define ID_USER_LOGING                  32779
#define ID_REPORT_MANAGE                32780
#define ID_SYS_SETTING                  32781
#define ID_CALIBRATE                    32782
#define ID_RECTITY_PICTURE              32783
#define ID_CAM_POSE_SET                 32784
#define ID_MODEL_SET                    32785
#define ID_MATCH_MODEL                  32786
#define ID_MEASURE_MANUAL               32787
#define ID_MEASURE_AUTO                 32788
#define ID_MEASURE_STOP                 32789
#define ID_COMBO_CAMERA_TYPE            32790
#define ID_COMBO_CAMERA_RESOLUTIION     32791
#define ID_BUTTON4                      32794
#define ID_BUTTON5                      32795
#define ID_BUT_ONLINE_INSPECT           32795
#define ID_CHECK2                       32796
#define ID_CHECK_X3                     32796
#define ID_COMBO4                       32797
#define ID_COMBO_CALI_CAMERA_MODEL      32797
#define ID_BUTTON6                      32798
#define ID_SLIDER1                      32799
#define ID_SYSLINK2                     32800
#define ID_CHECK_CAMERA_SOFT_TRIG       32801
#define ID_COMBO_CAMERA_CONNECT_TYPE    32802
#define ID_COMBO_CAMERA_NAME            32803
#define ID_EDIT_CAMERA_TRIG_TIME        32804
#define ID_CHECK_CAMERA_IS_RGB          32805
#define ID_BUTTON2                      32806
#define ID_BUT_COLOR_X3                 32806
#define ID_MEA_ELE_LINE                 32806
#define ID_BUTTON3                      32807
#define ID_BUT_CALI_INNER               32807
#define ID_CHECK3                       32808
#define ID_ROI_DRAW_CIRCLE              32810
#define ID_BUTTON9                      32811
#define ID_ROI_INFO                     32811
#define ID_BUTTON10                     32812
#define ID_BUTTON11                     32813
#define ID_COMBO2                       32814
#define ID_COMBO_MATCH_ROI_TYPE         32814
#define ID_SPIN1                        32815
#define ID_SPIN_X1                      32818
#define ID_SPIN_X2                      32819
#define ID_SPIN_X3                      32820
#define ID_SPIN_Y1                      32821
#define ID_SPIN_Y2                      32822
#define ID_SPIN_Y3                      32823
#define ID_BUT_COLOR_X1                 32824
#define ID_BUT_COLOR_X2                 32825
#define ID_CHECK_X1                     32826
#define ID_CHECK_X2                     32827
#define ID_EDIT2                        32828
#define ID_SPIN2                        32829
#define ID_CALIBRATE_INNER              32830
#define ID_BUT_CALI_CAPTURE             32831
#define ID_BUT_CALI_POSE                32832
#define ID_BUTTON_GEN_RECTIFY_MAP       32833
#define ID_COMBO_CALI_MAP_TYPE          32834
#define ID_EDIT3                        32835
#define ID_BUT_DRAW_SPOKE               32837
#define ID_EDIT4                        32839
#define ID_COMBO3                       32840
#define ID_BUT_FIND_MODEL               32841
#define ID_ROI_DRAW_RECTANGLE2          32842
#define ID_BUTTON_TAKE_ONE              32843
#define ID_BUT_RAKE_LINE                32844
#define ID_BUT_ROI_LINE_FIT             32845
#define ID_BUT_ROI_CIRCLE_FIT           32846
#define ID_BUT_OFF_LINE_MOLD            32847
#define ID_BALLOON_MOLDING              32848
#define ID_BALLOON_MEASURE              32849
#define ID_CHECK_CAMERA_EXPOSURE_MODE   32850
#define ID_CAMERA_GAIN_SPIN             32852
#define ID_CAMERA_EXPOSURE_TIME_SPIN    32853
#define ID_EDIT_EXPOSURE_TIIME          32855
#define ID_EDIT_CAMERA_GAIN             32856
#define ID_PROP_COMBOX                  32857
#define ID_VIEW_PROPERTY_BAR            32857
#define ID_VIEW_PICTUREVIEW             32858
#define ID_DEBUG_STARP                  32859
#define ID_DEBUG_STOP                   32860
#define ID_Menu                         32861
#define ID_PROJECT_RENAME               32862
#define ID_ProjectTreePaste             32863
#define ID_BUT_CALI_SHOW_INFO           32864
#define ID_BUT_CALI_DEL                 32865
#define ID_BUT_CALI_CORRECT             32866
#define ID_BUT_MATCH_LOAD_PIC           32867
#define ID_MATCH_TAKE_ONE               32868
#define ID_ROI_DEL_ALL_ROI              32869
#define ID_MATCH_DEL_ALL_ROI            32870
#define ID_ROI_DRAW_ELLIPSE             32871
#define ID_ROI_DRAW_RECTANGLE           32872
#define ID_ROI_DRAW_ANY_LINE            32873
#define ID_ROI_FIND_MODEL               32874
#define ID_MEA_ELE_CIRCLE               32875
#define ID_MEA_ELE_ARC                  32876
#define ID_MEA_ELE_ELLISPE              32877
#define ID_MEA_ELE_ELLISPE_ARC          32878
#define ID_MEA_ELE_WIDTH                32879
#define ID_MEA_ELE_FIND_EDGE            32880
#define ID_MEA_ELE_FIND_TOP             32881
#define ID_MEA_ELE_AREA                 32882
#define ID_MEA_ELE_COUNTER              32883
#define ID_MEA_ELE_BAR_1                32884
#define ID_MEA_ELE_BAR_2                32885
#define ID_MEA_ELE_MEASURE              32886
#define ID_MEA_ELE_LIST                 32887
#define ID_BUT_MATCH_SAVE_MODEL         32888
#define ID_MEA_ELE_DEL_ALL              32889
#define ID_ELE_ANGLE                    32890
#define ID_MEA_ELE_OUTPUT               32891
#define ID_ELE_DISTANCE                 32892
#define ID_MEA_ELE_CAMERA               32893
#define ID_MEA_ELE_function             32894
#define ID_AUTO_STOP                    32895
#define ID_AUTO_START                   32896
#define ID_MEA_ELE_STEP                 32897
#define ID_32898                        32898
#define ID_EXPORT_EXCEL                 32899
#define ID_MEA_ELE_MILLIMETER           32901
#define ID_DELETE_PRODUCT_RESULT        32902
#define ID_MEA_ELE_BALLOON_LENGTH       32903
#define ID_MEA_BALLOON_CENTER           32904
#define ID_MEA_BALLOON_ECCENT           32905
#define ID_MEA_ELE_BALLOON_FLAW         32906
#define ID_MEA_ELE_SAVE                 32908
#define ID_MEA_ELE_ROI                  32910
#define ID_BUT_USER_MANAGE              32911
#define ID_BUT_USER_MANAGE2             32911

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        340
#define _APS_NEXT_COMMAND_VALUE         32912
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
